name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        <!-- Please describe what happened here. -->
        
        ### Expected behavior
        <!-- Please describe what you expected to happen. -->

        ### Steps to reproduce
        <!-- Please describe the steps to reproduce the issue. -->

        ### Additional context
        <!-- Please provide any additional context that may help us understand the issue. -->

        ### Checklist
        - [ ] I have checked that the issue has not already been reported
        - [ ] I have included repoducible steps
        - [ ] I am using the latest version of the project (running off of main)
        - [ ] I have included any screenshots that may help out udnerstand the issue
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - MacOS
        - Linux
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell