name: Notify Discord on Assignments or Mentions

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, assigned]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install requests

      - name: Run notification script
        run: python notify_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          
      - name: Upload event dump
        uses: actions/upload-artifact@v3
        with:
          name: github-event-payload
          path: event_dump.json
