name: Notify Discord on Mentions

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install requests
        run: pip install requests

      - name: Notify Discord
        run: python notify_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      
      - name: Dump GitHub event payload
        run: cat "$GITHUB_EVENT_PATH"
